unit http_cmake_generator_tool;

// http_cmake_generator_tool - CMake build-script and test-driver
// generator for the LingoFuse HTTP/JSON ABI toolchain.
//
// This unit exposes two functions that together let the caller build
// and test the two C++ artifacts produced by the rest of the
// toolchain:
//
//     GenerateCMakeScript(Model)   -> CMakeLists.txt
//     GenerateTestMainCpp(Model)   -> test_main___.cpp
//
// The CMake project builds TWO executables:
//
//     <Unit>_http_json_service       (executable)
//         built from <Unit>_http_json_service.cpp produced by
//         http_cpp_abi_service_generator_tool.pas
//
//     <Unit>_http_json_call_test     (executable)
//         built from test_main___.cpp plus
//         <Unit>_http_json_call.cpp produced by
//         http_cpp_abi_call_generator_tool.pas
//
// Expected on-disk layout, all files in the SAME directory:
//
//     CMakeLists.txt
//     <Unit>_http_json_service.hpp
//     <Unit>_http_json_service.cpp
//     <Unit>_http_json_call.hpp
//     <Unit>_http_json_call.cpp
//     test_main___.cpp
//
// The path to the LingoFuse C++ distribution is NOT baked into the
// generated script. It is declared as a CACHE PATH variable named
// LINGOFUSE_CPP_LIB_DIR, so the user supplies it at configure time:
//
//     * in cmake-gui: fill the field
//           "LingoFuse C++ library directory"
//     * from a shell: pass
//           -DLINGOFUSE_CPP_LIB_DIR=/path/to/lf
//
// The directory must contain:
//
//     LingoFuse.h
//     LingoFuse.c
//     LingoFuse.hpp
//     lf_io.hpp
//     lf_http_bridge_client.hpp
//     json.hpp
//
// Revision notes (v3):
//
//   - LINGOFUSE_DIR was renamed to LINGOFUSE_CPP_LIB_DIR. The cache
//     description now reads "LingoFuse C++ library directory", which
//     is what appears in the cmake-gui field.
//
//   - All Windows runtime-DLL staging logic has been removed. Where
//     the DLLs live is a deployment concern that belongs to the user,
//     not to the build script.
//
//   - The test driver is now generated by this unit as
//     test_main___.cpp. GenerateTestMainCpp emits one try/catch block
//     per supported routine, using the same naming rules as
//     http_cpp_abi_call_generator_tool.pas so the emitted function
//     calls resolve to the call wrapper's public API.
//
//   - The CMake project expects test_main___.cpp, not test_main.cpp.
//
// Revision notes (v2):
//
//   - GenerateCode_LogEnabled is declared in the interface section, so
//     the Log helpers in the implementation can reference it. This
//     mirrors every other generator in this toolchain.
//
//   - Z.Status is in the uses clause because the Log helpers call
//     DoStatus.
//
// Author: LingoFuse-pasAgent project

{$DEFINE FPC_DELPHI_MODE}
{$I ..\..\zCore\src\Z.Define.inc}

interface

uses
  Z.Core,
  Z.PascalStrings, Z.UPascalStrings,
  Z.Status,
  Z.UnicodeMixedLib,
  Z.ListEngine,
  Z.Pascal_Func_Model;

const
  // Enable verbose logging during generation. Declared in the
  // interface so the Log helpers below can use it.
  GenerateCode_LogEnabled: boolean = False;

// GenerateCMakeScript - main entry point for the CMakeLists.txt.
//
// Model must be built with Typ_Normalize_Func = tnf_ABI. Only
// Model.UnitName is consulted.
//
// The returned list is owned by the caller and must be released with
// DisposeObject.
function GenerateCMakeScript(Model: TPascal_Func_Model): TPascalStringList;

// GenerateTestMainCpp - main entry point for the test driver.
//
// Emits one try/catch block per supported routine. Each block calls
// the wrapper function with default arguments (0 for integers, 0.0
// for floats, an empty string for strings) and reports success or
// failure on stdout/stderr. main() returns the number of failed calls
// clamped to 0/1.
//
// Model must be built with Typ_Normalize_Func = tnf_ABI.
//
// The returned list is owned by the caller and must be released with
// DisposeObject.
function GenerateTestMainCpp(Model: TPascal_Func_Model): TPascalStringList;

implementation

// -----------------------------------------------------------------------------
// Logging
// -----------------------------------------------------------------------------

procedure Log(const Msg: TP_String); overload;
begin
  if GenerateCode_LogEnabled then
    DoStatus('[http_cmake_generator] %s', [Msg.Text]);
end;

procedure Log(const Fmt: TP_String; const Args: array of const); overload;
begin
  if GenerateCode_LogEnabled then
    DoStatus('[http_cmake_generator] %s', [PFormat(Fmt, Args)]);
end;

// -----------------------------------------------------------------------------
// Identifier helpers
// -----------------------------------------------------------------------------
//
// These are deliberately identical to the ones in
// http_cpp_abi_call_generator_tool.pas. The test driver emitted by
// GenerateTestMainCpp must reference the same C++ identifiers that the
// call wrapper actually defines.

// NormalizeUnitName - mirror the normalization performed by every
// other generator in this toolchain.
//
// Replaced characters: space, tab, '.', '/', '\', '@', ':', '#', '?',
// '&', '=', '+', '-'. A leading digit is prefixed with '_'.
function NormalizeUnitName(const UnitName: U_String): U_String;
begin
  Result := UnitName.ReplaceChar(#32#9'./\@:#?&=+-', '_');
  if (Result.Len > 0) and (Result[1] >= '0') and (Result[1] <= '9') then
    Result := '_' + Result;
end;

// MakeApiName - canonicalize a routine name into the identifier used
// as the URL path segment. Must match every other generator in this
// toolchain.
function MakeApiName(const FuncName: U_String): U_String;
begin
  Result := FuncName.ReplaceChar(#32#9'./\@:#?&=+-', '_');
end;

// MakeSafeCppIdent - turn an arbitrary string into a valid C++
// identifier. Empty input yields a generated placeholder. Leading
// digits are prefixed with '_'. C++ reserved words are suffixed with
// '_'.
function MakeSafeCppIdent(const Name: U_String; Index: integer): U_String;
var
  i: integer;
  c: U_Char;
begin
  if Name.Len = 0 then
  begin
    Result := 'p' + umlIntToStr(Index);
    Exit;
  end;

  Result := '';
  for i := 1 to Name.Len do
  begin
    c := Name[i];
    if (c = '_') or ((c >= 'a') and (c <= 'z')) or ((c >= 'A') and (c <= 'Z')) or
      ((i > 1) and (c >= '0') and (c <= '9')) then
      Result.Append(c)
    else
      Result.Append('_');
  end;

  if (Result.Len > 0) and (Result[1] >= '0') and (Result[1] <= '9') then
    Result := '_' + Result;

  if Result.Same('alignas') or Result.Same('alignof') or Result.Same('and') or
    Result.Same('and_eq') or Result.Same('asm') or Result.Same('auto') or
    Result.Same('bitand') or Result.Same('bitor') or Result.Same('bool') or
    Result.Same('break') or Result.Same('case') or Result.Same('catch') or
    Result.Same('char') or Result.Same('char16_t') or Result.Same('char32_t') or
    Result.Same('class') or Result.Same('compl') or Result.Same('concept') or
    Result.Same('const') or Result.Same('constexpr') or Result.Same('const_cast') or
    Result.Same('continue') or Result.Same('co_await') or Result.Same('co_return') or
    Result.Same('co_yield') or Result.Same('decltype') or Result.Same('default') or
    Result.Same('delete') or Result.Same('do') or Result.Same('double') or
    Result.Same('dynamic_cast') or Result.Same('else') or Result.Same('enum') or
    Result.Same('explicit') or Result.Same('export') or Result.Same('extern') or
    Result.Same('false') or Result.Same('float') or Result.Same('for') or
    Result.Same('friend') or Result.Same('goto') or Result.Same('if') or
    Result.Same('inline') or Result.Same('int') or Result.Same('long') or
    Result.Same('mutable') or Result.Same('namespace') or Result.Same('new') or
    Result.Same('noexcept') or Result.Same('not') or Result.Same('not_eq') or
    Result.Same('nullptr') or Result.Same('operator') or Result.Same('or') or
    Result.Same('or_eq') or Result.Same('private') or Result.Same('protected') or
    Result.Same('public') or Result.Same('register') or Result.Same('reinterpret_cast') or
    Result.Same('requires') or Result.Same('return') or Result.Same('short') or
    Result.Same('signed') or Result.Same('sizeof') or Result.Same('static') or
    Result.Same('static_assert') or Result.Same('static_cast') or Result.Same('struct') or
    Result.Same('switch') or Result.Same('template') or Result.Same('this') or
    Result.Same('thread_local') or Result.Same('throw') or Result.Same('true') or
    Result.Same('try') or Result.Same('typedef') or Result.Same('typeid') or
    Result.Same('typename') or Result.Same('union') or Result.Same('unsigned') or
    Result.Same('using') or Result.Same('virtual') or Result.Same('void') or
    Result.Same('volatile') or Result.Same('wchar_t') or Result.Same('while') or
    Result.Same('xor') or Result.Same('xor_eq') then
    Result := Result + '_';
end;

// UniqueName - given a base identifier and a list of already-used
// identifiers, return a candidate that is not yet in the list.
function UniqueName(const Base: U_String; Used: TPascalStringList): U_String;
var
  i: integer;
begin
  if Used.IndexOf(Base) < 0 then
  begin
    Result := Base;
    Exit;
  end;
  i := 1;
  while Used.IndexOf(Base + '_' + umlIntToStr(i).Text) >= 0 do
    Inc(i);
  Result := Base + '_' + umlIntToStr(i).Text;
end;

// -----------------------------------------------------------------------------
// ABI type classification (mirrors the call generator)
// -----------------------------------------------------------------------------

function ABI_Type_Is_String(const T: U_String): boolean;
begin
  Result := T.Same('string') or T.Same('ansistring') or T.Same('unicodestring') or
    T.Same('tpascalstring') or T.Same('tupascalstring') or T.Same('tp_string') or
    T.Same('pchar') or T.Same('pansichar') or T.Same('pwidechar');
end;

function ABI_Type_Is_Float(const T: U_String): boolean;
begin
  Result := T.Same('double') or T.Same('single') or T.Same('extended') or T.Same('real');
end;

function ABI_Type_Is_Int(const T: U_String): boolean;
begin
  Result := T.Same('integer') or T.Same('int64') or T.Same('cardinal') or
    T.Same('longint') or T.Same('dword') or T.Same('word') or
    T.Same('smallint') or T.Same('byte') or T.Same('uint64') or T.Same('longword');
end;

function ABI_Type_Is_Supported(const T: U_String): boolean;
begin
  Result := ABI_Type_Is_String(T) or ABI_Type_Is_Float(T) or ABI_Type_Is_Int(T);
end;

function ABI_Type_To_Cpp_Decl(const T: U_String): U_String;
begin
  if ABI_Type_Is_String(T) then
    Result := 'std::string'
  else if ABI_Type_Is_Float(T) then
    Result := 'double'
  else if ABI_Type_Is_Int(T) then
    Result := 'std::int64_t'
  else
    Result := '';
end;

// ABI_Type_To_Cpp_Default_Arg - literal used as the default test
// argument for a parameter of this type.
function ABI_Type_To_Cpp_Default_Arg(const T: U_String): U_String;
begin
  if ABI_Type_Is_String(T) then
    Result := 'std::string()'
  else if ABI_Type_Is_Float(T) then
    Result := '0.0'
  else if ABI_Type_Is_Int(T) then
    Result := 'std::int64_t(0)'
  else
    Result := '{}';
end;

// -----------------------------------------------------------------------------
// Supported-function filtering (mirrors the call generator)
// -----------------------------------------------------------------------------

type
  TArryFunctionStructure = array of TFunctionStructure;

function CollectSupportedFunctions(Model: TPascal_Func_Model): TArryFunctionStructure;
var
  i, j: integer;
  f: TFunctionStructure;
  Supported: boolean;
begin
  SetLength(Result, 0);
  for i := 0 to Model.Funcs.Count - 1 do
  begin
    f := Model.Funcs[i];
    Supported := True;

    for j := 0 to High(f.Params) do
      if not ABI_Type_Is_Supported(f.Params[j].PascalType) then
      begin
        Supported := False;
        Log(PFormat('Skipped "%s": parameter "%s" has unsupported ABI type "%s"',
          [f.Name.Text, f.Params[j].Name.Text, f.Params[j].PascalType.Text]));
        Break;
      end;

    if Supported and f.IsFunction and (not ABI_Type_Is_Supported(f.ReturnType)) then
    begin
      Supported := False;
      Log(PFormat('Skipped "%s": return type "%s" is not a supported ABI type',
        [f.Name.Text, f.ReturnType.Text]));
    end;

    if Supported and (f.Name.Len = 0) then
    begin
      Supported := False;
      Log('Skipped: routine with empty Name');
    end;

    if Supported then
    begin
      SetLength(Result, Length(Result) + 1);
      Result[High(Result)] := f;
    end;
  end;
end;

// -----------------------------------------------------------------------------
// CMake script
// -----------------------------------------------------------------------------

procedure EmitPrologue(Lines: TPascalStringList;
  const ProjectName, UnitName: U_String);
begin
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('# ' + ProjectName.Text);
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('#');
  Lines.Add('# Auto-generated by http_cmake_generator_tool.pas.');
  Lines.Add('# Do not edit by hand unless you know what you are doing.');
  Lines.Add('#');
  Lines.Add('# Purpose: build and test the C++ service and call artifacts that');
  Lines.Add('# were generated for the Pascal unit "' + UnitName.Text + '".');
  Lines.Add('#');
  Lines.Add('# Targets:');
  Lines.Add('#');
  Lines.Add('#   ' + UnitName.Text + '_http_json_service       (executable)');
  Lines.Add('#       The service produced by');
  Lines.Add('#       http_cpp_abi_service_generator_tool.pas. It contains its');
  Lines.Add('#       own main() entry point.');
  Lines.Add('#');
  Lines.Add('#   ' + UnitName.Text + '_http_json_call_test     (executable)');
  Lines.Add('#       The test driver linked against the call wrapper produced by');
  Lines.Add('#       http_cpp_abi_call_generator_tool.pas.');
  Lines.Add('#');
  Lines.Add('# Expected files, all in this directory:');
  Lines.Add('#');
  Lines.Add('#   CMakeLists.txt');
  Lines.Add('#   ' + UnitName.Text + '_http_json_service.hpp');
  Lines.Add('#   ' + UnitName.Text + '_http_json_service.cpp');
  Lines.Add('#   ' + UnitName.Text + '_http_json_call.hpp');
  Lines.Add('#   ' + UnitName.Text + '_http_json_call.cpp');
  Lines.Add('#   test_main___.cpp');
  Lines.Add('#');
  Lines.Add('# HOW TO CONFIGURE');
  Lines.Add('# ----------------');
  Lines.Add('#');
  Lines.Add('# Point LINGOFUSE_CPP_LIB_DIR at the LingoFuse C++ library');
  Lines.Add('# directory, which must contain:');
  Lines.Add('#');
  Lines.Add('#   LingoFuse.h, LingoFuse.c, LingoFuse.hpp, lf_io.hpp,');
  Lines.Add('#   lf_http_bridge_client.hpp, json.hpp');
  Lines.Add('#');
  Lines.Add('# In cmake-gui, fill in the field');
  Lines.Add('#     "LingoFuse C++ library directory".');
  Lines.Add('# From a shell, pass it explicitly:');
  Lines.Add('#     cmake -S . -B build -DLINGOFUSE_CPP_LIB_DIR=/path/to/lf');
  Lines.Add('#');
  Lines.Add('# HOW TO RUN');
  Lines.Add('# ----------');
  Lines.Add('#');
  Lines.Add('# After the build completes, start bridge.py (see the service');
  Lines.Add('# README), then launch the service executable, then launch the');
  Lines.Add('# test executable. Make sure the LingoFuse dynamic library is');
  Lines.Add('# reachable from the executables: either copy it next to them or');
  Lines.Add('# add its directory to PATH / LD_LIBRARY_PATH. This project does');
  Lines.Add('# not stage the DLLs.');
  Lines.Add('#');
  Lines.Add('# NOTE ON LANGUAGES');
  Lines.Add('# -----------------');
  Lines.Add('# "C CXX" is required as the project language list. LingoFuse.c');
  Lines.Add('# is a C source file; CMake cannot pick a link language for a');
  Lines.Add('# target that mixes .c and .cpp files when only CXX is enabled.');
  Lines.Add('#');
  Lines.Add('');
  Lines.Add('cmake_minimum_required(VERSION 3.15)');
  Lines.Add('');
  Lines.Add('project(' + ProjectName.Text + ' C CXX)');
  Lines.Add('');
  Lines.Add('set(CMAKE_CXX_STANDARD 17)');
  Lines.Add('set(CMAKE_CXX_STANDARD_REQUIRED ON)');
  Lines.Add('set(CMAKE_CXX_EXTENSIONS OFF)');
  Lines.Add('');
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('# LingoFuse C++ library directory');
  Lines.Add('#');
  Lines.Add('# LINGOFUSE_CPP_LIB_DIR is a CACHE PATH entry. It appears in');
  Lines.Add('# cmake-gui as a browsable directory field and can also be set');
  Lines.Add('# from the command line with -DLINGOFUSE_CPP_LIB_DIR=... .');
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('');
  Lines.Add('set(LINGOFUSE_CPP_LIB_DIR "" CACHE PATH "LingoFuse C++ library directory")');
  Lines.Add('');
  Lines.Add('if(NOT EXISTS "${LINGOFUSE_CPP_LIB_DIR}/LingoFuse.h")');
  Lines.Add('    message(FATAL_ERROR');
  Lines.Add('        "LINGOFUSE_CPP_LIB_DIR does not point at a LingoFuse C++ "');
  Lines.Add('        "library directory (LingoFuse.h was not found). "');
  Lines.Add('        "Current value: ''${LINGOFUSE_CPP_LIB_DIR}''. "');
  Lines.Add('        "Set it in cmake-gui or pass "');
  Lines.Add('        "-DLINGOFUSE_CPP_LIB_DIR=/path/to/lf on the cmake command line.")');
  Lines.Add('endif()');
  Lines.Add('');
  Lines.Add('set(LINGOFUSE_C_SOURCE    "${LINGOFUSE_CPP_LIB_DIR}/LingoFuse.c")');
  Lines.Add('set(LINGOFUSE_INCLUDE_DIR "${LINGOFUSE_CPP_LIB_DIR}")');
  Lines.Add('');
  Lines.Add('set(PROJECT_DIR "${CMAKE_CURRENT_SOURCE_DIR}")');
  Lines.Add('');
end;

procedure EmitWarningFlags(Lines: TPascalStringList;
  const TargetName: U_String);
begin
  Lines.Add('if(MSVC)');
  Lines.Add('    target_compile_options(' + TargetName.Text +
    ' PRIVATE /W4 /permissive-)');
  Lines.Add('else()');
  Lines.Add('    target_compile_options(' + TargetName.Text +
    ' PRIVATE -Wall -Wextra)');
  Lines.Add('endif()');
  Lines.Add('');
end;

procedure EmitLinkLibraries(Lines: TPascalStringList;
  const TargetName: U_String);
begin
  Lines.Add('if(WIN32)');
  Lines.Add('    target_link_libraries(' + TargetName.Text + ' PRIVATE ws2_32)');
  Lines.Add('elseif(APPLE)');
  Lines.Add('    find_package(Threads REQUIRED)');
  Lines.Add('    target_link_libraries(' + TargetName.Text + ' PRIVATE Threads::Threads)');
  Lines.Add('else()');
  Lines.Add('    find_package(Threads REQUIRED)');
  Lines.Add('    target_link_libraries(' + TargetName.Text + ' PRIVATE');
  Lines.Add('        Threads::Threads ${CMAKE_DL_LIBS})');
  Lines.Add('endif()');
  Lines.Add('');
end;

procedure EmitServiceTarget(Lines: TPascalStringList;
  const UnitName: U_String);
var
  TargetName, ServiceHpp, ServiceCpp: U_String;
begin
  TargetName := UnitName + '_http_json_service';
  ServiceHpp := UnitName + '_http_json_service.hpp';
  ServiceCpp := UnitName + '_http_json_service.cpp';

  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('# Service executable');
  Lines.Add('#');
  Lines.Add('# Built from ' + ServiceCpp.Text + ', which is produced by');
  Lines.Add('# http_cpp_abi_service_generator_tool.pas. That source file');
  Lines.Add('# contains its own main() entry point, so the target is an');
  Lines.Add('# executable rather than a library.');
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('');
  Lines.Add('set(SERVICE_HPP "${PROJECT_DIR}/' + ServiceHpp.Text + '")');
  Lines.Add('set(SERVICE_CPP "${PROJECT_DIR}/' + ServiceCpp.Text + '")');
  Lines.Add('');
  Lines.Add('if(NOT EXISTS "${SERVICE_CPP}")');
  Lines.Add('    message(FATAL_ERROR');
  Lines.Add('        "Missing generated service source file: ''${SERVICE_CPP}''. "');
  Lines.Add('        "Run http_cpp_abi_service_generator_tool.pas and place its "');
  Lines.Add('        "output next to this CMakeLists.txt.")');
  Lines.Add('endif()');
  Lines.Add('');
  Lines.Add('add_executable(' + TargetName.Text);
  Lines.Add('    "${SERVICE_CPP}"');
  Lines.Add('    "${LINGOFUSE_C_SOURCE}"');
  Lines.Add(')');
  Lines.Add('');
  Lines.Add('target_include_directories(' + TargetName.Text + ' PRIVATE');
  Lines.Add('    "${PROJECT_DIR}"');
  Lines.Add('    "${LINGOFUSE_INCLUDE_DIR}"');
  Lines.Add(')');
  Lines.Add('');
  EmitWarningFlags(Lines, TargetName);
  EmitLinkLibraries(Lines, TargetName);
end;

procedure EmitCallTestTarget(Lines: TPascalStringList;
  const UnitName: U_String);
var
  TargetName, CallHpp, CallCpp, TestMain: U_String;
begin
  TargetName := UnitName + '_http_json_call_test';
  CallHpp := UnitName + '_http_json_call.hpp';
  CallCpp := UnitName + '_http_json_call.cpp';
  TestMain := 'test_main___.cpp';

  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('# Call test executable');
  Lines.Add('#');
  Lines.Add('# Built from ' + TestMain.Text + ' (produced by');
  Lines.Add('# http_cmake_generator_tool.pas) and ' + CallCpp.Text + ' (produced');
  Lines.Add('# by http_cpp_abi_call_generator_tool.pas). The test driver');
  Lines.Add('# prepares LingoFuse, sets HTTP_CALL_BASE_URL, and calls every');
  Lines.Add('# supported wrapper function with default arguments.');
  Lines.Add('# ---------------------------------------------------------------------');
  Lines.Add('');
  Lines.Add('set(CALL_HPP  "${PROJECT_DIR}/' + CallHpp.Text + '")');
  Lines.Add('set(CALL_CPP  "${PROJECT_DIR}/' + CallCpp.Text + '")');
  Lines.Add('set(TEST_MAIN "${PROJECT_DIR}/' + TestMain.Text + '")');
  Lines.Add('');
  Lines.Add('if(NOT EXISTS "${CALL_CPP}")');
  Lines.Add('    message(FATAL_ERROR');
  Lines.Add('        "Missing generated call source file: ''${CALL_CPP}''. "');
  Lines.Add('        "Run http_cpp_abi_call_generator_tool.pas and place its "');
  Lines.Add('        "output next to this CMakeLists.txt.")');
  Lines.Add('endif()');
  Lines.Add('');
  Lines.Add('if(NOT EXISTS "${TEST_MAIN}")');
  Lines.Add('    message(FATAL_ERROR');
  Lines.Add('        "Missing test driver: ''${TEST_MAIN}''. "');
  Lines.Add('        "Run http_cmake_generator_tool.pas to generate it.")');
  Lines.Add('endif()');
  Lines.Add('');
  Lines.Add('add_executable(' + TargetName.Text);
  Lines.Add('    "${TEST_MAIN}"');
  Lines.Add('    "${CALL_CPP}"');
  Lines.Add('    "${LINGOFUSE_C_SOURCE}"');
  Lines.Add(')');
  Lines.Add('');
  Lines.Add('target_include_directories(' + TargetName.Text + ' PRIVATE');
  Lines.Add('    "${PROJECT_DIR}"');
  Lines.Add('    "${LINGOFUSE_INCLUDE_DIR}"');
  Lines.Add(')');
  Lines.Add('');
  EmitWarningFlags(Lines, TargetName);
  EmitLinkLibraries(Lines, TargetName);
end;

function GenerateCMakeScript(Model: TPascal_Func_Model): TPascalStringList;
var
  UnitName, Normalized, ProjectName: U_String;
  Lines: TPascalStringList;
begin
  Result := nil;
  if Model = nil then
  begin
    Log('GenerateCMakeScript: Model is nil');
    Exit;
  end;

  UnitName := Model.UnitName;
  if UnitName.Len = 0 then
  begin
    Log('GenerateCMakeScript: UnitName is empty');
    Exit;
  end;

  Normalized := NormalizeUnitName(UnitName);
  ProjectName := Normalized + '_http_json_test';

  Lines := TPascalStringList.Create;
  try
    EmitPrologue(Lines, ProjectName, Normalized);
    EmitServiceTarget(Lines, Normalized);
    EmitCallTestTarget(Lines, Normalized);

    Result := Lines;
    Log(PFormat('Generated CMake script: %d lines, project "%s".',
      [Lines.Count, ProjectName.Text]));
  except
    DisposeObject(Lines);
    raise;
  end;
end;

// -----------------------------------------------------------------------------
// Test driver (test_main___.cpp)
// -----------------------------------------------------------------------------

// EmitTestCall - one try/catch block for a single routine.
procedure EmitTestCall(Lines: TPascalStringList;
  const Ns, CppFuncName, ApiName: U_String;
  const F: TFunctionStructure);
var
  i: integer;
  Args: U_String;
  ArgList: U_String;
begin
  Lines.Add('    // ---- ' + ApiName.Text + ' ----');
  Lines.Add('    try {');

  ArgList := '';
  for i := 0 to High(F.Params) do
  begin
    if i > 0 then
      ArgList := ArgList + ', ';
    Args := ABI_Type_To_Cpp_Default_Arg(F.Params[i].PascalType);
    ArgList := ArgList + Args;
  end;

  if F.IsFunction then
  begin
    Lines.Add('        auto r = ' + Ns.Text + '::' + CppFuncName.Text +
      '(' + ArgList.Text + ');');
    Lines.Add('        std::printf("' + ApiName.Text + ': OK\n");');
    Lines.Add('        (void)r;');
  end
  else
  begin
    Lines.Add('        ' + Ns.Text + '::' + CppFuncName.Text +
      '(' + ArgList.Text + ');');
    Lines.Add('        std::printf("' + ApiName.Text + ': OK\n");');
  end;

  Lines.Add('    } catch (const ' + Ns.Text + '::HTTPCallError& e) {');
  Lines.Add('        std::fprintf(stderr,');
  Lines.Add('            "' + ApiName.Text +
    ': FAILED: %s (code=%d, http_status=%d)\n",');
  Lines.Add('            e.what(), e.code, e.http_status);');
  Lines.Add('        ++failures;');
  Lines.Add('    } catch (const std::exception& e) {');
  Lines.Add('        std::fprintf(stderr,');
  Lines.Add('            "' + ApiName.Text +
    ': UNEXPECTED EXCEPTION: %s\n", e.what());');
  Lines.Add('        ++failures;');
  Lines.Add('    }');
  Lines.Add('');
end;

function GenerateTestMainCpp(Model: TPascal_Func_Model): TPascalStringList;
var
  UnitName, Normalized, Ns, Endpoint, BaseUrl: U_String;
  SupportedFuncs: TArryFunctionStructure;
  UsedApiNames, ApiNames: TPascalStringList;
  UsedCppFuncNames, CppFuncNames: TPascalStringList;
  ApiName, CppFuncName: U_String;
  i: integer;
  f: TFunctionStructure;
  Lines: TPascalStringList;
begin
  Result := nil;
  if Model = nil then
  begin
    Log('GenerateTestMainCpp: Model is nil');
    Exit;
  end;

  UnitName := Model.UnitName;
  if UnitName.Len = 0 then
  begin
    Log('GenerateTestMainCpp: UnitName is empty');
    Exit;
  end;

  Normalized := NormalizeUnitName(UnitName);
  Ns := Normalized.LowerText;
  Endpoint := 'ipc:' + Normalized + '_http_json';
  BaseUrl := 'http://127.0.0.1:8081/' + Normalized;

  SupportedFuncs := CollectSupportedFunctions(Model);

  UsedApiNames := TPascalStringList.Create;
  ApiNames := TPascalStringList.Create;
  UsedCppFuncNames := TPascalStringList.Create;
  CppFuncNames := TPascalStringList.Create;
  Lines := TPascalStringList.Create;
  try
    for i := 0 to High(SupportedFuncs) do
    begin
      ApiName := UniqueName(MakeApiName(SupportedFuncs[i].Name), UsedApiNames);
      UsedApiNames.Add(ApiName);
      ApiNames.Add(ApiName);

      CppFuncName := UniqueName(MakeSafeCppIdent(ApiName, i), UsedCppFuncNames);
      UsedCppFuncNames.Add(CppFuncName);
      CppFuncNames.Add(CppFuncName);
    end;

    // -------------------------------------------------------------------------
    // File header
    // -------------------------------------------------------------------------
    Lines.Add('// Auto-generated by http_cmake_generator_tool.pas.');
    Lines.Add('// Source model unit: ' + UnitName.Text + '.');
    Lines.Add('// Do not edit by hand unless you know what you are doing.');
    Lines.Add('//');
    Lines.Add('// Test driver for the ' + Normalized.Text + '_http_json_call wrapper.');
    Lines.Add('//');
    Lines.Add('// What this program does:');
    Lines.Add('//');
    Lines.Add('//   1. Loads the LingoFuse dynamic library through');
    Lines.Add('//      lingofuse::LibraryLoader.');
    Lines.Add('//   2. Prepares a client connection to the LingoFuse endpoint');
    Lines.Add('//      "' + Endpoint.Text + '".');
    Lines.Add('//   3. Points the call wrapper at the bridge by setting');
    Lines.Add('//      HTTP_CALL_BASE_URL.');
    Lines.Add('//   4. Calls every supported wrapper function with default');
    Lines.Add('//      arguments and reports success or failure for each.');
    Lines.Add('//   5. Returns 0 when all calls succeeded, 1 otherwise.');
    Lines.Add('//');
    Lines.Add('// Prerequisite: bridge.py must be running on the same LingoFuse');
    Lines.Add('// endpoint, and the service executable must be running too.');
    Lines.Add('');
    Lines.Add('#include "' + Normalized.Text + '_http_json_call.hpp"');
    Lines.Add('#include "LingoFuse.hpp"');
    Lines.Add('');
    Lines.Add('#include <cstdint>');
    Lines.Add('#include <cstdio>');
    Lines.Add('#include <exception>');
    Lines.Add('#include <string>');
    Lines.Add('');
    Lines.Add('int main() {');
    Lines.Add('    lingofuse::LibraryLoader loader;');
    Lines.Add('');
    Lines.Add('    lingofuse::resetPrepare();');
    Lines.Add('    lingofuse::prepareClient("' + Endpoint.Text + '", nullptr);');
    Lines.Add('    if (lingofuse::prepareDone() != 1) {');
    Lines.Add('        std::fprintf(stderr, "LingoFuse init failed\n");');
    Lines.Add('        return 1;');
    Lines.Add('    }');
    Lines.Add('');
    Lines.Add('    ' + Ns.Text + '::HTTP_CALL_BASE_URL = "'
      + BaseUrl.Text + '";');
    Lines.Add('');
    Lines.Add('    int failures = 0;');
    Lines.Add('');

    if Length(SupportedFuncs) = 0 then
    begin
      Lines.Add('    // No supported routines were generated for this unit.');
      Lines.Add('    std::printf("no routines to test\n");');
    end
    else
    begin
      for i := 0 to High(SupportedFuncs) do
      begin
        f := SupportedFuncs[i];
        ApiName := ApiNames[i];
        CppFuncName := CppFuncNames[i];
        EmitTestCall(Lines, Ns, CppFuncName, ApiName, f);
      end;
    end;

    Lines.Add('    lingofuse::exitMainThread();');
    Lines.Add('    lingofuse::shutdown();');
    Lines.Add('');
    Lines.Add('    if (failures == 0) {');
    Lines.Add('        std::printf("all calls succeeded\n");');
    Lines.Add('        return 0;');
    Lines.Add('    }');
    Lines.Add('    std::fprintf(stderr, "%d call(s) failed\n", failures);');
    Lines.Add('    return 1;');
    Lines.Add('}');

    Result := Lines;
    Log(PFormat('Generated test driver: %d lines, %d routines.',
      [Lines.Count, Length(SupportedFuncs)]));
  finally
    UsedApiNames.Free;
    ApiNames.Free;
    UsedCppFuncNames.Free;
    CppFuncNames.Free;
    if Result <> Lines then
      Lines.Free;
  end;
end;

end.
