(*
  * =============================================================================
  * cpp_mcp_generator_tool - C++ MCP tool provider code & doc generator
  * =============================================================================
  *
  * Produces three files from one TPascal_Func_Model:
  *
  *   1. <unit>_tool_provider.hpp   -> GenerateHPPCode
  *   2. <unit>_tool_provider.cpp   -> GenerateCPPCode
  *   3. <unit>_tool_provider_cpp.md -> GenerateCPPReadme
  *
  * Filtering rules (shared by all three generators):
  *   1. Unsupported declarations are dropped (see IsDeclSupported).
  *   2. Duplicate tool names are dropped: MCP tool names must be unique,
  *      because both the LingoFuse beacon and the MCP protocol key on the
  *      tool name alone. Overloaded Pascal routines therefore collapse to
  *      the first declaration; the rest are skipped and logged.
  *
  * All comments and status output are in English.
  * =============================================================================
*)

unit cpp_mcp_generator_tool;

{$DEFINE FPC_DELPHI_MODE}
{$I ..\..\zCore\src\Z.Define.inc}

{$IFDEF FPC}
  {$CODEPAGE UTF8}
{$ENDIF FPC}

interface

uses
  Z.Core,
  Z.PascalStrings, Z.UPascalStrings,
  Z.Status,
  Z.Json,
  Z.UnicodeMixedLib,
  Z.ListEngine,
  Z.Pascal_Func_Model,
  Z.Parsing;

{* Generate the C++ header (.hpp). Caller owns the returned list. *}
function GenerateHPPCode(Model: TPascal_Func_Model): TPascalStringList;

{* Generate the C++ implementation (.cpp). Caller owns the returned list. *}
function GenerateCPPCode(Model: TPascal_Func_Model): TPascalStringList;

{* Generate the English Markdown README (.md). Caller owns the returned list. *}
function GenerateCPPReadme(Model: TPascal_Func_Model): TPascalStringList;

var
  GenerateCode_LogEnabled: boolean = False;

implementation

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const
  DEFAULT_APP_DESC = 'Tool provider generated by cpp_mcp_generator_tool';
  DEFAULT_IPC_ENDPOINT = 'ipc:agent';
  DEFAULT_BEACON_APP = 'agent_main_app';
  DEFAULT_REGISTER_API = 'register_agent';
  DEFAULT_AGENT_LOG_API = 'agent_log';
  MAX_DESC_LEN = 200;

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

type
  TValidFuncArray = array of TFunctionStructure;

// -----------------------------------------------------------------------------
// Logging
// -----------------------------------------------------------------------------

procedure Log(const Msg: TP_String);
begin
  if GenerateCode_LogEnabled then
    DoStatus('[cpp_mcp_generator_tool] ' + Msg);
end;

procedure LogFmt(const Fmt: TP_String; const Args: array of const);
begin
  if GenerateCode_LogEnabled then
    DoStatus('[cpp_mcp_generator_tool] ' + PFormat(Fmt, Args));
end;

// -----------------------------------------------------------------------------
// Type helpers
// -----------------------------------------------------------------------------

function IsSupportedType(const Typ: TP_String): boolean;
begin
  Result := Typ.Same('int64', 'double', 'string');
end;

function PascalTypeToCPPType(const Typ: TP_String; const AsReturn: boolean): TP_String;
begin
  if Typ.Same('int64') then
    Result := 'std::int64_t'
  else if Typ.Same('double') then
    Result := 'double'
  else if Typ.Same('string') then
  begin
    if AsReturn then
      Result := 'std::string'
    else
      Result := 'const std::string&';
  end
  else
    Result := 'void';
end;

function PascalTypeToDefaultValue(const Typ: TP_String): TP_String;
begin
  if Typ.Same('int64') then Result := '0'
  else if Typ.Same('double') then Result := '0.0'
  else if Typ.Same('string') then Result := 'std::string()'
  else Result := '0';
end;

function PascalTypeToJsonSchemaType(const Typ: TP_String): TP_String;
begin
  if Typ.Same('int64') then Result := 'integer'
  else if Typ.Same('double') then Result := 'number'
  else if Typ.Same('string') then Result := 'string'
  else Result := 'string';
end;

function PascalTypeToJsonLiteral(const Typ: TP_String): TP_String;
begin
  if Typ.Same('int64') then Result := '0'
  else if Typ.Same('double') then Result := '0.0'
  else if Typ.Same('string') then Result := '""'
  else Result := 'null';
end;

// -----------------------------------------------------------------------------
// Name helpers
// -----------------------------------------------------------------------------

function MakeApiName(const FuncName: TP_String): TP_String;
var
  i: integer;
  c: TP_Char;
begin
  Result := '';
  for i := 1 to FuncName.Len do
  begin
    c := FuncName[i];
    if ((c >= 'a') and (c <= 'z')) or ((c >= 'A') and (c <= 'Z')) or
       ((c >= '0') and (c <= '9')) or (c = '_') then
      Result := Result + c
    else
      Result := Result + '_';
  end;
  if Result.Len = 0 then
    Result := 'unnamed';
end;

function MakeCallbackName(const ApiName: TP_String): TP_String;
begin
  Result := 'callback_' + MakeApiName(ApiName);
end;

function MakeInternalCallName(const ApiName: TP_String): TP_String;
begin
  Result := 'internal_call_' + MakeApiName(ApiName);
end;

function MakeIncludeGuardName(const UnitName: TP_String): TP_String;
var
  i: integer;
  c: TP_Char;
begin
  Result := '';
  for i := 1 to UnitName.Len do
  begin
    c := UnitName[i];
    if (c >= 'a') and (c <= 'z') then
      Result := Result + TP_Char(Chr(Ord(c) - 32))
    else if (c >= 'A') and (c <= 'Z') then
      Result := Result + c
    else if (c >= '0') and (c <= '9') then
      Result := Result + c
    else
      Result := Result + '_';
  end;
  if Result.Len = 0 then
    Result := 'TOOL_PROVIDER';
  Result := Result + '_HPP';
end;

function MakeSourceFileName(const UnitName: TP_String): TP_String;
begin
  Result := MakeApiName(UnitName).LowerText + '_tool_provider';
end;

function MakeAppNameFromUnit(const UnitName: TP_String): TP_String;
var
  tmp: TP_String;
begin
  tmp := UnitName;
  if umlMultipleMatch('*.pas', tmp) then
    tmp := umlChangeFileExt(tmp.Text, '').Text;
  Result := tmp.ReplaceChar('.', '_').ReplaceChar('-', '_');
end;

// -----------------------------------------------------------------------------
// String literal escaping for C++
// -----------------------------------------------------------------------------

function CPPStrLit(const S: TP_String): TP_String;
var
  i: integer;
  c: TP_Char;
begin
  Result := '"';
  for i := 1 to S.Len do
  begin
    c := S[i];
    if c = '"' then
      Result := Result + '\"'
    else if c = '\' then
      Result := Result + '\\'
    else if c = #10 then
      Result := Result + '\n'
    else if c = #13 then
      Result := Result + '\r'
    else if c = #9 then
      Result := Result + '\t'
    else
      Result := Result + c;
  end;
  Result := Result + '"';
end;

// -----------------------------------------------------------------------------
// Comment normalisation
// -----------------------------------------------------------------------------

function CleanComment_Local(const Cmt: TP_String): TP_String;
var
  Parser: TTextParsing;
  i: integer;
  Token: PTokenData;
  Parts: TP_ArrayString;
  Part: TP_String;
begin
  Result := '';
  if Cmt = '' then Exit;

  Parser := TTextParsing.Create(Cmt, tsPascal);
  try
    SetLength(Parts, 0);
    for i := 0 to Parser.TokenCount - 1 do
    begin
      Token := Parser.Tokens[i];
      if Token^.tokenType = ttComment then
      begin
        Part := TTextParsing.Translate_Pascal_Decl_Comment_To_Text(Token^.Text);
        Part := Part.TrimChar(#32#9#13#10);
        if Part <> '' then
        begin
          SetLength(Parts, Length(Parts) + 1);
          Parts[High(Parts)] := Part;
        end;
      end;
    end;

    Result := '';
    for i := 0 to High(Parts) do
    begin
      if i > 0 then Result := Result + #10;
      Result := Result + Parts[i];
    end;
  finally
    Parser.Free;
  end;
end;

function GetFullDescription(const Comment: TP_String): TP_String;
var
  Cleaned: TP_String;
  Lines: TPascalStringList;
  i: integer;
  S: TP_String;
begin
  Result := '';
  if Comment = '' then Exit;

  Cleaned := CleanComment_Local(Comment);
  if Cleaned = '' then Exit;

  Lines := TPascalStringList.Create;
  try
    umlSeparatorText(Cleaned, Lines, #10);
    for i := 0 to Lines.Count - 1 do
    begin
      S := TP_String(Lines[i]);
      while (S.Len > 0) and ((S.Last = #13) or (S.Last = #10)) do
        S.DeleteLast;
      S := S.TrimChar(#32#9);
      if S.Len = 0 then Continue;
      if S[1] = '@' then Continue;
      if Result.Len > 0 then
        Result := Result + ' ';
      Result := Result + S;
    end;
  finally
    Lines.Free;
  end;

  if Result.Len > MAX_DESC_LEN then
    Result := Result.GetString(1, MAX_DESC_LEN + 1);
end;

function GetTableCellText(const Comment: TP_String): TP_String;
begin
  Result := GetFullDescription(Comment);
  Result := Result.ReplaceChar('|', '/');
  Result := Result.ReplaceChar(#13#10, ' ');
  Result := Result.TrimChar(#32#9);
  if Result.Len = 0 then
    Result := '(no description)';
end;

// -----------------------------------------------------------------------------
// Filtering
// -----------------------------------------------------------------------------

function IsDeclSupported(const F: TFunctionStructure): boolean;
var
  j: integer;
begin
  Result := False;
  if F.Name.Len = 0 then Exit;
  for j := 0 to High(F.Params) do
  begin
    if F.Params[j].Name.Len = 0 then Exit;
    if not IsSupportedType(F.Params[j].PascalType) then Exit;
  end;
  if F.IsFunction then
    if not IsSupportedType(F.ReturnType) then Exit;
  Result := True;
end;

function CollectValidFunctions(Model: TPascal_Func_Model): TValidFuncArray;
var
  i, Idx: integer;
  F: TFunctionStructure;
  SeenNames: TPascalStringList;
begin
  SetLength(Result, 0);
  if (Model = nil) or (Model.FuncCount <= 0) then Exit;

  SetLength(Result, Model.FuncCount);
  Idx := 0;

  SeenNames := TPascalStringList.Create;
  try
    for i := 0 to Model.FuncCount - 1 do
    begin
      F := Model.Funcs[i];

      if not IsDeclSupported(F) then
      begin
        LogFmt('  Skipped "%s": unsupported declaration', [F.Name.Text]);
        Continue;
      end;

      if SeenNames.ExistsValue(F.Name.Text) >= 0 then
      begin
        LogFmt('  Skipped "%s": duplicate tool name (MCP requires unique names)',
          [F.Name.Text]);
        Continue;
      end;

      SeenNames.Add(F.Name.Text);
      Result[Idx] := F;
      Inc(Idx);
    end;
  finally
    SeenNames.Free;
  end;

  SetLength(Result, Idx);
end;

// =============================================================================
// SECTION 1 - HPP generator
// =============================================================================

function GenerateHPPCode(Model: TPascal_Func_Model): TPascalStringList;
var
  L: TPascalStringList;
  i, j: integer;
  F: TFunctionStructure;
  ValidFuncs: TValidFuncArray;
  guard: TP_String;
  params_str: TP_String;
  ret_type: TP_String;
  desc: TP_String;
  tmp: TP_String;
begin
  Result := TPascalStringList.Create;
  L := Result;

  guard := MakeIncludeGuardName(Model.UnitName);

  LogFmt('GenerateHPPCode: unit="%s" raw=%d',
    [Model.UnitName.Text, Model.FuncCount]);

  ValidFuncs := CollectValidFunctions(Model);
  LogFmt('GenerateHPPCode: %d valid functions after filtering',
    [Length(ValidFuncs)]);

  L.Add('// Auto-generated by cpp_mcp_generator_tool');
  L.Add('// Source unit: ' + Model.UnitName.Text);
  L.Add('// Do not edit this file manually.');
  L.Add('');
  L.Add('#ifndef ' + guard);
  L.Add('#define ' + guard);
  L.Add('');
  L.Add('#include "LingoFuse.h"');
  L.Add('');
  L.Add('#include <cstdint>');
  L.Add('#include <string>');
  L.Add('');
  L.Add('// ==================== Application metadata ====================');
  L.Add('');
  L.Add('extern const char* MY_APP_NAME;');
  L.Add('extern const char* MY_APP_DESC;');
  L.Add('extern const char* IPC_ENDPOINT;');
  L.Add('extern const char* BEACON_APP;');
  L.Add('extern const char* REGISTER_API;');
  L.Add('extern const char* AGENT_LOG_API;');
  L.Add('extern const bool  DEBUG_LOG;');
  L.Add('');
  L.Add('// ==================== Internal call declarations ====================');
  L.Add('// These functions must be implemented by the user.');
  L.Add('');

  for i := 0 to High(ValidFuncs) do
  begin
    F := ValidFuncs[i];

    desc := GetFullDescription(F.Comment);
    if desc.Len > 0 then
      L.Add('// ' + desc.Text);

    tmp := '';
    for j := 0 to High(F.Params) do
    begin
      if j > 0 then tmp := tmp + ', ';
      tmp := tmp + PascalTypeToCPPType(F.Params[j].PascalType, False) +
        ' ' + F.Params[j].Name.Text;
    end;
    params_str := tmp;

    if F.IsFunction then
      ret_type := PascalTypeToCPPType(F.ReturnType, True)
    else
      ret_type := 'void';

    L.Add(ret_type + ' ' + MakeInternalCallName(F.Name) + '(' + params_str + ');');
    L.Add('');
    LogFmt('  HPP: emitted "%s"', [F.Name.Text]);
  end;

  L.Add('// ==================== Registration entry points ====================');
  L.Add('');
  L.Add('TAppHnd RegisterAPIs();');
  L.Add('bool    RegisterTools();');
  L.Add('bool    Execute_And_Reg_all();');
  L.Add('');
  L.Add('#endif // ' + guard);

  LogFmt('GenerateHPPCode: done, %d lines', [L.Count]);
end;

// =============================================================================
// SECTION 2 - CPP generator
// =============================================================================

function BuildCPPParamDecl(const F: TFunctionStructure): TP_String;
var
  j: integer;
begin
  Result := '';
  for j := 0 to High(F.Params) do
  begin
    if j > 0 then Result := Result + ', ';
    Result := Result + PascalTypeToCPPType(F.Params[j].PascalType, False) +
      ' ' + F.Params[j].Name.Text;
  end;
end;

function BuildCPPArgList(const F: TFunctionStructure): TP_String;
var
  j: integer;
begin
  Result := '';
  for j := 0 to High(F.Params) do
  begin
    if j > 0 then Result := Result + ', ';
    Result := Result + F.Params[j].Name.Text;
  end;
end;

procedure EmitHelpers(L: TPascalStringList);
begin
  L.Add('// ==================== Helper functions ====================');
  L.Add('');
  L.Add('static std::string read_string(TDataHnd hnd)');
  L.Add('{');
  L.Add('    const std::int64_t pos  = LF_GetPos(hnd);');
  L.Add('    const std::int64_t size = LF_GetSize(hnd);');
  L.Add('    if (pos < 0 || pos >= size)');
  L.Add('        return std::string();');
  L.Add('    const auto* base =');
  L.Add('        static_cast<const std::uint8_t*>(LF_GetBuffer(hnd));');
  L.Add('    if (base == nullptr)');
  L.Add('        return std::string();');
  L.Add('    std::int64_t end = pos;');
  L.Add('    while (end < size && base[end] != 0)');
  L.Add('        ++end;');
  L.Add('    std::string result(');
  L.Add('        reinterpret_cast<const char*>(base + pos),');
  L.Add('        static_cast<std::size_t>(end - pos));');
  L.Add('    LF_SetPos(hnd, end + 1);');
  L.Add('    return result;');
  L.Add('}');
  L.Add('');
  L.Add('static void write_string(TDataHnd hnd, const std::string& s)');
  L.Add('{');
  L.Add('    if (!s.empty())');
  L.Add('        LF_WriteBuffer(hnd, s.data(),');
  L.Add('                       static_cast<std::int64_t>(s.size()));');
  L.Add('    const char nul = 0;');
  L.Add('    LF_WriteBuffer(hnd, &nul, 1);');
  L.Add('}');
  L.Add('');
  L.Add('static json read_json(TDataHnd hnd)');
  L.Add('{');
  L.Add('    const std::string s = read_string(hnd);');
  L.Add('    if (s.empty())');
  L.Add('        return json();');
  L.Add('    try');
  L.Add('    {');
  L.Add('        return json::parse(s);');
  L.Add('    }');
  L.Add('    catch (...)');
  L.Add('    {');
  L.Add('        return json();');
  L.Add('    }');
  L.Add('}');
  L.Add('');
  L.Add('static void write_json(TDataHnd hnd, const json& obj)');
  L.Add('{');
  L.Add('    write_string(hnd, obj.dump(-1, ' + #39 + ' ' + #39 + ', false,');
  L.Add('                             json::error_handler_t::replace));');
  L.Add('}');
  L.Add('');
  L.Add('static void send_log_async(const std::string& msg)');
  L.Add('{');
  L.Add('    if (!DEBUG_LOG)');
  L.Add('        return;');
  L.Add('    TDataHnd req = LF_CreateData(AGENT_LOG_API);');
  L.Add('    if (req == nullptr)');
  L.Add('        return;');
  L.Add('    try');
  L.Add('    {');
  L.Add('        json payload;');
  L.Add('        payload["message"] = msg;');
  L.Add('        write_json(req, payload);');
  L.Add('        TDataHnd resp = LF_Call(BEACON_APP, req, 5000);');
  L.Add('        if (resp != nullptr)');
  L.Add('            LF_FreeData(resp);');
  L.Add('    }');
  L.Add('    catch (...) {}');
  L.Add('    LF_FreeData(req);');
  L.Add('}');
  L.Add('');
end;

procedure EmitInternalCalls(L: TPascalStringList; const ValidFuncs: TValidFuncArray);
var
  i: integer;
  F: TFunctionStructure;
  params_decl: TP_String;
  ret_type: TP_String;
  default_val: TP_String;
begin
  L.Add('// ==================== Internal call implementations (TODO) ====================');
  L.Add('//');
  L.Add('// Replace each placeholder body with the actual implementation.');
  L.Add('// The generated callbacks below will invoke these functions.');
  L.Add('');

  for i := 0 to High(ValidFuncs) do
  begin
    F := ValidFuncs[i];

    params_decl := BuildCPPParamDecl(F);

    if F.IsFunction then
    begin
      ret_type := PascalTypeToCPPType(F.ReturnType, True);
      default_val := PascalTypeToDefaultValue(F.ReturnType);
    end
    else
    begin
      ret_type := 'void';
      default_val := '';
    end;

    L.Add(ret_type + ' ' + MakeInternalCallName(F.Name) + '(' + params_decl + ')');
    L.Add('{');
    L.Add('    // TODO: replace this placeholder with the actual implementation.');
    if F.IsFunction then
      L.Add('    return ' + default_val.Text + ';');
    L.Add('}');
    L.Add('');
  end;
end;

procedure EmitCallbacks(L: TPascalStringList; const ValidFuncs: TValidFuncArray);
var
  i, j: integer;
  F: TFunctionStructure;
  json_key: TP_String;
  args_str: TP_String;
begin
  L.Add('// ==================== Callbacks (cdecl) ====================');
  L.Add('');

  for i := 0 to High(ValidFuncs) do
  begin
    F := ValidFuncs[i];

    L.Add('static void LF_CDECL ' + MakeCallbackName(F.Name) + '(void* _Trigger, void* _In, void* _Out)');
    L.Add('{');
    L.Add('    (void)_Trigger;');
    L.Add('    TDataHnd in_hnd  = static_cast<TDataHnd>(_In);');
    L.Add('    TDataHnd out_hnd = static_cast<TDataHnd>(_Out);');
    L.Add('');
    L.Add('    try');
    L.Add('    {');
    L.Add('        json req = read_json(in_hnd);');
    L.Add('        if (!req.is_object())');
    L.Add('            req = json::object();');
    L.Add('');

    for j := 0 to High(F.Params) do
    begin
      json_key := F.Params[j].Name.Text;
      if F.Params[j].PascalType.Same('int64') then
        L.Add('        std::int64_t ' + F.Params[j].Name.Text + ' = req.value(' + CPPStrLit(json_key) + ', static_cast<std::int64_t>(0));')
      else if F.Params[j].PascalType.Same('double') then
        L.Add('        double ' + F.Params[j].Name.Text + ' = req.value(' + CPPStrLit(json_key) + ', 0.0);')
      else if F.Params[j].PascalType.Same('string') then
        L.Add('        std::string ' + F.Params[j].Name.Text + ' = req.value(' + CPPStrLit(json_key) + ', std::string());');
    end;

    args_str := BuildCPPArgList(F);

    L.Add('');
    if F.IsFunction then
    begin
      L.Add('        auto ret = ' + MakeInternalCallName(F.Name) + '(' + args_str + ');');
      L.Add('');
      L.Add('        json resp;');
      L.Add('        resp["result"] = ret;');
      L.Add('        write_json(out_hnd, resp);');
    end
    else
    begin
      L.Add('        ' + MakeInternalCallName(F.Name) + '(' + args_str + ');');
      L.Add('');
      L.Add('        json resp;');
      L.Add('        resp["status"] = "ok";');
      L.Add('        write_json(out_hnd, resp);');
    end;

    L.Add('    }');
    L.Add('    catch (const std::exception& e)');
    L.Add('    {');
    L.Add('        try');
    L.Add('        {');
    L.Add('            json err;');
    L.Add('            err["error"] = std::string(e.what());');
    L.Add('            write_json(out_hnd, err);');
    L.Add('        }');
    L.Add('        catch (...) {}');
    L.Add('    }');
    L.Add('    catch (...)');
    L.Add('    {');
    L.Add('        try');
    L.Add('        {');
    L.Add('            json err;');
    L.Add('            err["error"] = std::string("unknown exception");');
    L.Add('            write_json(out_hnd, err);');
    L.Add('        }');
    L.Add('        catch (...) {}');
    L.Add('    }');
    L.Add('}');
    L.Add('');
  end;
end;

procedure EmitRegistration(L: TPascalStringList; const ValidFuncs: TValidFuncArray);
var
  i, j: integer;
  F: TFunctionStructure;
  desc: TP_String;
  param_desc: TP_String;
  ValidCount: integer;
begin
  ValidCount := Length(ValidFuncs);

  L.Add('// ==================== Registration ====================');
  L.Add('');
  L.Add('TAppHnd RegisterAPIs()');
  L.Add('{');
  L.Add('    TAppHnd app = LF_CreateApp(MY_APP_NAME, MY_APP_DESC);');
  L.Add('    if (app == nullptr)');
  L.Add('    {');
  L.Add('        send_log_async("Failed to create App.");');
  L.Add('        return nullptr;');
  L.Add('    }');
  L.Add('');

  for i := 0 to High(ValidFuncs) do
  begin
    F := ValidFuncs[i];
    desc := GetFullDescription(F.Comment);

    L.Add('    if (LF_RegisterCall(app,');
    L.Add('                       ' + CPPStrLit(F.Name) + ',');
    L.Add('                       ' + CPPStrLit(desc) + ',');
    L.Add('                       nullptr,');
    L.Add('                       &' + MakeCallbackName(F.Name) + ') != 1)');
    L.Add('    {');
    L.Add('        send_log_async(std::string("Failed to register API: ") + ' + CPPStrLit(F.Name) + ');');
    L.Add('        LF_FreeApp(app);');
    L.Add('        return nullptr;');
    L.Add('    }');
    L.Add('');
  end;

  L.Add('    return app;');
  L.Add('}');
  L.Add('');

  L.Add('static bool RegisterOneTool(const char* name,');
  L.Add('                            const char* description,');
  L.Add('                            const json& parameters_schema)');
  L.Add('{');
  L.Add('    TDataHnd req = LF_CreateData(REGISTER_API);');
  L.Add('    if (req == nullptr)');
  L.Add('        return false;');
  L.Add('');
  L.Add('    bool ok = false;');
  L.Add('    try');
  L.Add('    {');
  L.Add('        json payload;');
  L.Add('        payload["name"]        = std::string(name);');
  L.Add('        payload["description"] = std::string(description);');
  L.Add('        payload["target_app"]  = std::string(MY_APP_NAME);');
  L.Add('        payload["target_api"]  = std::string(name);');
  L.Add('        payload["parameters"]  = parameters_schema;');
  L.Add('        write_json(req, payload);');
  L.Add('');
  L.Add('        TDataHnd resp = LF_Call(BEACON_APP, req, 5000);');
  L.Add('        if (resp != nullptr)');
  L.Add('        {');
  L.Add('            try');
  L.Add('            {');
  L.Add('                json r = read_json(resp);');
  L.Add('                ok = (r.value("status", std::string()) == "ok");');
  L.Add('            }');
  L.Add('            catch (...) { ok = false; }');
  L.Add('            LF_FreeData(resp);');
  L.Add('        }');
  L.Add('    }');
  L.Add('    catch (...) { ok = false; }');
  L.Add('    LF_FreeData(req);');
  L.Add('    return ok;');
  L.Add('}');
  L.Add('');

  L.Add('bool RegisterTools()');
  L.Add('{');
  L.Add('    int registered = 0;');
  L.Add('');

  for i := 0 to High(ValidFuncs) do
  begin
    F := ValidFuncs[i];
    desc := GetFullDescription(F.Comment);

    L.Add('    {');
    L.Add('        json parameters_schema;');
    L.Add('        parameters_schema["type"] = "object";');
    L.Add('        json props    = json::object();');
    L.Add('        json required = json::array();');
    L.Add('');

    for j := 0 to High(F.Params) do
    begin
      param_desc := GetFullDescription(F.Params[j].Description);
      L.Add('        {');
      L.Add('            json p;');
      L.Add('            p["type"] = ' + CPPStrLit(PascalTypeToJsonSchemaType(F.Params[j].PascalType)) + ';');
      if param_desc.Len > 0 then
        L.Add('            p["description"] = ' + CPPStrLit(param_desc) + ';');
      L.Add('            props[' + CPPStrLit(F.Params[j].Name) + '] = p;');
      L.Add('            required.push_back(' + CPPStrLit(F.Params[j].Name) + ');');
      L.Add('        }');
    end;

    L.Add('');
    L.Add('        parameters_schema["properties"] = props;');
    L.Add('        parameters_schema["required"]   = required;');
    L.Add('');
    L.Add('        if (RegisterOneTool(' + CPPStrLit(F.Name) + ',');
    L.Add('                           ' + CPPStrLit(desc) + ',');
    L.Add('                           parameters_schema))');
    L.Add('        {');
    L.Add('            ++registered;');
    L.Add('        }');
    L.Add('    }');
    L.Add('');
  end;

  L.Add('    if (DEBUG_LOG)');
  L.Add('    {');
  L.Add('        send_log_async("RegisterTools: " +');
  L.Add('                       std::to_string(registered) + "/' + umlIntToStr(ValidCount) + ' tools registered.");');
  L.Add('    }');
  L.Add('    return registered > 0;');
  L.Add('}');
  L.Add('');

  L.Add('bool Execute_And_Reg_all()');
  L.Add('{');
  L.Add('    TAppHnd app = RegisterAPIs();');
  L.Add('    if (app == nullptr)');
  L.Add('        return false;');
  L.Add('');
  L.Add('    LF_ResetPrepare();');
  L.Add('    if (LF_PrepareClient(IPC_ENDPOINT, app) == -1)');
  L.Add('    {');
  L.Add('        send_log_async("LF_PrepareClient failed.");');
  L.Add('        LF_FreeApp(app);');
  L.Add('        return false;');
  L.Add('    }');
  L.Add('');
  L.Add('    if (LF_PrepareDone() <= 0)');
  L.Add('    {');
  L.Add('        send_log_async("LF_PrepareDone failed.");');
  L.Add('        LF_FreeApp(app);');
  L.Add('        return false;');
  L.Add('    }');
  L.Add('');
  L.Add('    return RegisterTools();');
  L.Add('}');
  L.Add('');
end;

function GenerateCPPCode(Model: TPascal_Func_Model): TPascalStringList;
var
  L: TPascalStringList;
  ValidFuncs: TValidFuncArray;
  hpp_name: TP_String;
begin
  Result := TPascalStringList.Create;
  L := Result;

  hpp_name := MakeSourceFileName(Model.UnitName) + '.hpp';

  LogFmt('GenerateCPPCode: unit="%s" raw=%d hpp="%s"',
    [Model.UnitName.Text, Model.FuncCount, hpp_name.Text]);

  ValidFuncs := CollectValidFunctions(Model);
  LogFmt('GenerateCPPCode: %d valid functions after filtering',
    [Length(ValidFuncs)]);

  L.Add('// Auto-generated by cpp_mcp_generator_tool');
  L.Add('// Source unit: ' + Model.UnitName.Text);
  L.Add('');
  L.Add('#include "' + hpp_name + '"');
  L.Add('');
  L.Add('#include <cstdint>');
  L.Add('#include <string>');
  L.Add('#include <exception>');
  L.Add('');
  L.Add('#include "json.hpp"');
  L.Add('');
  L.Add('using json = nlohmann::json;');
  L.Add('');

  L.Add('// ==================== Application metadata ====================');
  L.Add('');
  L.Add('extern const char* MY_APP_NAME   = ' + CPPStrLit(Model.UnitName) + ';');
  L.Add('extern const char* MY_APP_DESC   = ' + CPPStrLit(DEFAULT_APP_DESC) + ';');
  L.Add('extern const char* IPC_ENDPOINT  = ' + CPPStrLit(DEFAULT_IPC_ENDPOINT) + ';');
  L.Add('extern const char* BEACON_APP    = ' + CPPStrLit(DEFAULT_BEACON_APP) + ';');
  L.Add('extern const char* REGISTER_API  = ' + CPPStrLit(DEFAULT_REGISTER_API) + ';');
  L.Add('extern const char* AGENT_LOG_API = ' + CPPStrLit(DEFAULT_AGENT_LOG_API) + ';');
  L.Add('extern const bool  DEBUG_LOG     = false;');
  L.Add('');

  EmitHelpers(L);
  EmitInternalCalls(L, ValidFuncs);
  EmitCallbacks(L, ValidFuncs);
  EmitRegistration(L, ValidFuncs);

  LogFmt('GenerateCPPCode: done, %d lines', [L.Count]);
end;

// =============================================================================
// SECTION 3 - C++ README generator (English Markdown)
// =============================================================================

function GenerateCPPReadme(Model: TPascal_Func_Model): TPascalStringList;
var
  L: TPascalStringList;
  ValidFuncs: TValidFuncArray;
  UnitName, AppName: TP_String;
  hpp_name, cpp_name: TP_String;
  i, j: integer;
  f: TFunctionStructure;
  desc, shortDesc, row: TP_String;

  procedure EmitHeader;
  begin
    L.Add('# ' + UnitName + ' - C++ Tool Provider');
    L.Add('');
    L.Add('> **Auto-generated**. Produced by `cpp_mcp_generator_tool.pas`;');
    L.Add('> stays in sync with the code files.');
    L.Add('>');
    L.Add('> **Source unit**     : `' + UnitName + '`');
    L.Add('> **Header file**     : `' + hpp_name + '`');
    L.Add('> **Implementation**  : `' + cpp_name + '`');
    L.Add('> **Exposed APIs**    : ' + umlIntToStr(Length(ValidFuncs)).Text);
    L.Add('');
    L.Add('---');
    L.Add('');
  end;

  procedure EmitOverview;
  begin
    L.Add('## 1. Overview');
    L.Add('');
    L.Add('This README explains how to build, integrate, and test the');
    L.Add('auto-generated C++ tool provider: `' + hpp_name + '` plus');
    L.Add('`' + cpp_name + '`.');
    L.Add('');
    L.Add('The provider registers every top-level function of `' + UnitName + '`');
    L.Add('as a LingoFuse Call API and advertises each API as an MCP tool through');
    L.Add('the beacon. An LLM client discovers these tools through the beacon and');
    L.Add('invokes them over IPC.');
    L.Add('');
    L.Add('### 1.1 Dependencies');
    L.Add('');
    L.Add('| Dependency | Purpose | Availability |');
    L.Add('|------------|---------|--------------|');
    L.Add('| `json.hpp` (nlohmann/json) | JSON parse / serialize | Single-header, https://github.com/nlohmann/json |');
    L.Add('| `LingoFuse.h` | C ABI declarations for all `LF_*` functions | See section 1.2 |');
    L.Add('| `LingoFuse64.dll` / `liblingofuse.so` | Runtime library | Ships with the LingoFuse runtime |');
    L.Add('| `pascal_agent_service.exe` | Beacon server that routes tool calls | Built from `<v3>/src/pascal_agent_service.lpr` |');
    L.Add('| `mcp_api_tool.py` | MCP gateway that exposes tools to LLM clients | Ships with v3 at `<v3>/src/mcp_api_tool.py` |');
    L.Add('');
    L.Add('### 1.2 Status of the C++ companion repository (`cppAgent`)');
    L.Add('');
    L.Add('A dedicated **`cppAgent`** repository is planned to ship:');
    L.Add('');
    L.Add('- `LingoFuse.h` (the C ABI header, matching `lingofuse_import.pas`)');
    L.Add('- A CMake package config (`find_package(LingoFuse)`)');
    L.Add('- A working sample C++ provider');
    L.Add('');
    L.Add('**At the time of this writing the `cppAgent` repository has not been');
    L.Add('published yet.** Until it is, obtain the header from one of these');
    L.Add('sources:');
    L.Add('');
    L.Add('| Source | Where |');
    L.Add('|--------|-------|');
    L.Add('| The LingoFuse runtime distribution | `LingoFuse.h` next to `LingoFuse64.dll` / `liblingofuse.so` |');
    L.Add('| The `LingoFuse-pasAgent-v3` repository | Translate the declarations in `<v3>/src/lingofuse_import.pas` to C++ |');
    L.Add('| Hand-written, minimal | Copy only the LF_* prototypes referenced by the generated `.cpp` (see section 3.1) |');
    L.Add('');
    L.Add('> **Placeholder note**: `<cppagent-repo-url>` is a literal placeholder.');
    L.Add('> Replace it with the actual clone URL of `cppAgent` once it becomes');
    L.Add('> available. Until then, follow one of the fallback options above.');
    L.Add('');
    L.Add('### 1.3 Files produced by this generator');
    L.Add('');
    L.Add('| File | Purpose |');
    L.Add('|------|---------|');
    L.Add('| `' + hpp_name + '` | Public header: metadata externs, internal-call declarations, entry points |');
    L.Add('| `' + cpp_name + '` | Implementation: helpers, callbacks, registration, entry points |');
    L.Add('| `' + UnitName + '_tool_provider_cpp.md` | This README |');
    L.Add('');
  end;

  procedure EmitArchitecture;
  begin
    L.Add('## 2. Runtime Architecture');
    L.Add('');
    L.Add('```mermaid');
    L.Add('flowchart TD');
    L.Add('    subgraph Runtime["LingoFuse Runtime"]');
    L.Add('        BEACON["pascal_agent_service.exe<br/>(agent_main_app)"]');
    L.Add('        IPC["ipc:agent"]');
    L.Add('    end');
    L.Add('');
    L.Add('    subgraph Provider["Generated C++ Provider"]');
    L.Add('        REG_APIS["RegisterAPIs()<br/>create App + register Call APIs"]');
    L.Add('        PREPARE["LF_PrepareClient + LF_PrepareDone"]');
    L.Add('        REG_TOOLS["RegisterTools()<br/>advertise tools to beacon"]');
    L.Add('    end');
    L.Add('');
    L.Add('    subgraph Tools["Exposed APIs"]');
    L.Add('        T_API["Call APIs from ' + UnitName + '"]');
    L.Add('    end');
    L.Add('');
    L.Add('    subgraph Client["LLM / MCP Client"]');
    L.Add('        LLM["mcp_api_tool.py<br/>LM Studio / Claude / ..."]');
    L.Add('    end');
    L.Add('');
    L.Add('    BEACON <--> IPC');
    L.Add('    REG_APIS --> PREPARE');
    L.Add('    PREPARE --> IPC');
    L.Add('    REG_TOOLS --> BEACON');
    L.Add('    LLM -->|discover| BEACON');
    L.Add('    LLM -->|invoke| IPC');
    L.Add('    IPC --> T_API');
    L.Add('');
    L.Add('    style Runtime fill:#e3f2fd,stroke:#1565c0');
    L.Add('    style Provider fill:#fff3e0,stroke:#e65100');
    L.Add('    style Tools fill:#e8f5e9,stroke:#2e7d32');
    L.Add('    style Client fill:#f3e5f5,stroke:#6a1b9a');
    L.Add('```');
    L.Add('');
    L.Add('**Call chain**');
    L.Add('');
    L.Add('1. Start `pascal_agent_service.exe` (the beacon); it listens on');
    L.Add('   `ipc:agent`.');
    L.Add('2. Start the C++ provider executable; it calls `Execute_And_Reg_all`.');
    L.Add('3. `RegisterAPIs` creates a LingoFuse App and registers every top-level');
    L.Add('   function of `' + UnitName + '` as a Call API.');
    L.Add('4. `LF_PrepareClient` connects to `ipc:agent`; `LF_PrepareDone` waits');
    L.Add('   for readiness.');
    L.Add('5. `RegisterTools` pushes the JSON schema of every API to the beacon.');
    L.Add('6. An MCP client (`mcp_api_tool.py` + LM Studio / Claude) discovers');
    L.Add('   the tools and invokes them over IPC.');
    L.Add('');
  end;

  procedure EmitTestProgram;
  begin
    L.Add('## 3. Test Program (`main.cpp`)');
    L.Add('');
    L.Add('The program below is a **complete, copy-paste-ready** C++ entry point');
    L.Add('that compiles the generated provider into a runnable executable. Save');
    L.Add('it as `main.cpp` in the same directory as the generated files.');
    L.Add('');
    L.Add('Key points:');
    L.Add('');
    L.Add('- **No LF_* prototypes are declared here.** They come from');
    L.Add('  `' + hpp_name + '`, which itself includes `LingoFuse.h`.');
    L.Add('- The generated `' + cpp_name + '` provides the external symbols');
    L.Add('  (`MY_APP_NAME`, `MY_APP_DESC`, `IPC_ENDPOINT`, `BEACON_APP`,');
    L.Add('  `REGISTER_API`, `AGENT_LOG_API`, `DEBUG_LOG`) and the three entry');
    L.Add('  points (`RegisterAPIs`, `RegisterTools`, `Execute_And_Reg_all`).');
    L.Add('- `LF_ExitMainThread()` then `LF_Shutdown()` release all LingoFuse');
    L.Add('  resources cleanly.');
    L.Add('');
    L.Add('```cpp');
    L.Add('// main.cpp - test entry point for the generated C++ tool provider.');
    L.Add('//');
    L.Add('// Build (Linux/macOS, g++):');
    L.Add('//   g++ -std=c++17 -O2 -I. main.cpp \\');
    L.Add('//       ' + cpp_name + ' \\');
    L.Add('//       -L/path/to/lingofuse/lib -lLingoFuse \\');
    L.Add('//       -o ' + MakeApiName(AppName).LowerText + '_provider');
    L.Add('//');
    L.Add('// Build (Windows, MSVC, from a Developer Command Prompt):');
    L.Add('//   cl /std:c++17 /EHsc /I. main.cpp ' + cpp_name + ' \\');
    L.Add('//      /link /LIBPATH:C:\\path\\to\\lingofuse\\lib LingoFuse.lib');
    L.Add('');
    L.Add('#include "' + hpp_name + '"');
    L.Add('');
    L.Add('#include <cstdio>');
    L.Add('#include <cstdlib>');
    L.Add('#include <string>');
    L.Add('');
    L.Add('// Minimal forward declarations for the two teardown functions.');
    L.Add('// They are part of the LingoFuse C ABI; declaring them here keeps');
    L.Add('// this file self-contained if you prefer not to include LingoFuse.h');
    L.Add('// in main.cpp. If you DO include LingoFuse.h, remove these two lines.');
    L.Add('extern "C" void LF_ExitMainThread();');
    L.Add('extern "C" void LF_Shutdown();');
    L.Add('');
    L.Add('int main()');
    L.Add('{');
    L.Add('    std::printf("=== %s Tool Provider ===\\n", MY_APP_NAME);');
    L.Add('    std::printf("Connecting to %s ...\\n", IPC_ENDPOINT);');
    L.Add('');
    L.Add('    if (!Execute_And_Reg_all())');
    L.Add('    {');
    L.Add('        std::fprintf(stderr, "\\n[FATAL] Provider startup failed.\\n");');
    L.Add('        std::fprintf(stderr, "Checklist:\\n");');
    L.Add('        std::fprintf(stderr, "  1. Is pascal_agent_service.exe running?\\n");');
    L.Add('        std::fprintf(stderr, "  2. Is the endpoint %s reachable?\\n", IPC_ENDPOINT);');
    L.Add('        std::fprintf(stderr, "  3. See DEBUG_LOG output above for details.\\n");');
    L.Add('        return 1;');
    L.Add('    }');
    L.Add('');
    L.Add('    std::printf("\\n[OK] Provider is ready. All tools registered.\\n");');
    L.Add('    std::printf("Press Enter to shut down.\\n");');
    L.Add('    std::getchar();');
    L.Add('');
    L.Add('    LF_ExitMainThread();');
    L.Add('    LF_Shutdown();');
    L.Add('    std::printf("[OK] Shutdown complete.\\n");');
    L.Add('    return 0;');
    L.Add('}');
    L.Add('```');
    L.Add('');
    L.Add('### 3.1 Minimal `LingoFuse.h` fallback');
    L.Add('');
    L.Add('If the official `LingoFuse.h` is not yet available to you, the');
    L.Add('following minimal header is sufficient to compile the generated');
    L.Add('provider. It declares only the symbols actually used.');
    L.Add('');
    L.Add('```cpp');
    L.Add('// LingoFuse.h - minimal fallback declaration set.');
    L.Add('// Replace with the official header when cppAgent becomes available.');
    L.Add('#pragma once');
    L.Add('');
    L.Add('#include <cstdint>');
    L.Add('');
    L.Add('#ifdef _WIN32');
    L.Add('#  define LF_CDECL __cdecl');
    L.Add('#else');
    L.Add('#  define LF_CDECL');
    L.Add('#endif');
    L.Add('');
    L.Add('extern "C" {');
    L.Add('');
    L.Add('using TDataHnd = void*;');
    L.Add('using TAppHnd  = void*;');
    L.Add('');
    L.Add('using LFCallFunc   = void (LF_CDECL*)(void*, void*, void*);');
    L.Add('using LFNotifyFunc = void (LF_CDECL*)(void*, void*);');
    L.Add('');
    L.Add('// Data handle operations');
    L.Add('TDataHnd LF_CreateData(const char* methodName);');
    L.Add('void     LF_FreeData(TDataHnd hnd);');
    L.Add('void*    LF_GetBuffer(TDataHnd hnd);');
    L.Add('std::int64_t LF_WriteBuffer(TDataHnd hnd, const void* buff, std::int64_t size);');
    L.Add('std::int64_t LF_ReadBuffer(TDataHnd hnd, void* buff, std::int64_t size);');
    L.Add('std::int64_t LF_GetPos(TDataHnd hnd);');
    L.Add('void     LF_SetPos(TDataHnd hnd, std::int64_t pos);');
    L.Add('std::int64_t LF_GetSize(TDataHnd hnd);');
    L.Add('void     LF_SetSize(TDataHnd hnd, std::int64_t size);');
    L.Add('');
    L.Add('// Application handle operations');
    L.Add('TAppHnd LF_CreateApp(const char* appName, const char* desc);');
    L.Add('void    LF_FreeApp(TAppHnd appHnd);');
    L.Add('int     LF_RegisterCall(TAppHnd appHnd,');
    L.Add('                        const char* methodName,');
    L.Add('                        const char* desc,');
    L.Add('                        void* trigger,');
    L.Add('                        LFCallFunc onCall);');
    L.Add('int     LF_RegisterNotify(TAppHnd appHnd,');
    L.Add('                          const char* methodName,');
    L.Add('                          const char* desc,');
    L.Add('                          void* trigger,');
    L.Add('                          LFNotifyFunc onNotify);');
    L.Add('int     LF_Unregister(TAppHnd appHnd, const char* methodName);');
    L.Add('');
    L.Add('// Network preparation and remote calls');
    L.Add('void LF_ResetPrepare();');
    L.Add('int  LF_PrepareClient(const char* physicsAddr, TAppHnd appHnd);');
    L.Add('int  LF_PrepareService(const char* listeningAddr, const char* physicsAddr);');
    L.Add('int  LF_PrepareDone();');
    L.Add('void LF_ExitMainThread();');
    L.Add('void LF_Shutdown();');
    L.Add('');
    L.Add('TDataHnd LF_Call(const char* appName, TDataHnd param, std::uint64_t timeoutMs);');
    L.Add('void     LF_Notify(const char* appName, TDataHnd param);');
    L.Add('void     LF_Sequenced_Notify(const char* appName, TDataHnd param);');
    L.Add('');
    L.Add('// Runtime options and status');
    L.Add('void LF_SetOption(const char* option, const char* value);');
    L.Add('int  LF_GetStatusCount();');
    L.Add('const char* LF_GetStatus();');
    L.Add('void LF_PostStatus(const char* status);');
    L.Add('int  LF_CheckMainThread();');
    L.Add('int  LF_CheckApp(const char* appName);');
    L.Add('int  LF_CheckApi(const char* appName, const char* apiName);');
    L.Add('');
    L.Add('} // extern "C"');
    L.Add('```');
    L.Add('');
  end;

  procedure EmitBuildTestProcedure;
  begin
    L.Add('## 4. Build & Test Procedure');
    L.Add('');
    L.Add('Follow the steps in order. Each step is independent and can be');
    L.Add('verified before moving on.');
    L.Add('');
    L.Add('```mermaid');
    L.Add('flowchart TD');
    L.Add('    S1["1. Prepare env<br/>(LingoFuse.h, json.hpp, lib)"]');
    L.Add('    S2["2. Compile main.cpp<br/>+ provider.cpp"]');
    L.Add('    S3["3. Start beacon<br/>(pascal_agent_service.exe)"]');
    L.Add('    S4["4. Start provider<br/>(./provider)"]');
    L.Add('    S5["5. Start mcp_api_tool<br/>+ generate client config"]');
    L.Add('    S6["6. Start agent<br/>(LM Studio / Claude / ...)"]');
    L.Add('    S7["7. Test API<br/>(invoke tool from agent)"]');
    L.Add('');
    L.Add('    S1 --> S2 --> S3 --> S4 --> S5 --> S6 --> S7');
    L.Add('');
    L.Add('    style S1 fill:#e3f2fd');
    L.Add('    style S2 fill:#fff3e0');
    L.Add('    style S3 fill:#e8f5e9');
    L.Add('    style S4 fill:#fff7e6');
    L.Add('    style S5 fill:#f3e5f5');
    L.Add('    style S6 fill:#fce4ec');
    L.Add('    style S7 fill:#e0f7fa');
    L.Add('```');
    L.Add('');

    L.Add('### Step 1 - Prepare the environment');
    L.Add('');
    L.Add('Create a directory for the provider, then place:');
    L.Add('');
    L.Add('```');
    L.Add('my_cpp_provider/');
    L.Add('  ' + hpp_name);
    L.Add('  ' + cpp_name);
    L.Add('  main.cpp');
    L.Add('  json.hpp            <- from nlohmann/json');
    L.Add('  LingoFuse.h         <- official header, or the fallback from section 3.1');
    L.Add('  libLingoFuse.so     <- shared library (Linux)');
    L.Add('  LingoFuse64.dll     <- shared library (Windows)');
    L.Add('```');
    L.Add('');
    L.Add('Download `json.hpp` from https://github.com/nlohmann/json/releases');
    L.Add('(the single-include `json.hpp` is enough; no other files are needed).');
    L.Add('');

    L.Add('### Step 2 - Compile');
    L.Add('');
    L.Add('**Linux / macOS**:');
    L.Add('');
    L.Add('```bash');
    L.Add('g++ -std=c++17 -O2 -I. \\');
    L.Add('    main.cpp ' + cpp_name + ' \\');
    L.Add('    -L. -lLingoFuse \\');
    L.Add('    -Wl,-rpath,. \\');
    L.Add('    -o ' + MakeApiName(AppName).LowerText + '_provider');
    L.Add('```');
    L.Add('');
    L.Add('**Windows (MSVC)**: from a Developer Command Prompt:');
    L.Add('');
    L.Add('```bat');
    L.Add('cl /std:c++17 /EHsc /I. main.cpp ' + cpp_name + ' ^');
    L.Add('   /link /LIBPATH:. LingoFuse.lib /OUT:' + MakeApiName(AppName).LowerText + '_provider.exe');
    L.Add('```');
    L.Add('');
    L.Add('**Windows (MinGW-w64)**:');
    L.Add('');
    L.Add('```bat');
    L.Add('g++ -std=c++17 -O2 -I. main.cpp ' + cpp_name + ' ^');
    L.Add('    -L. -lLingoFuse -o ' + MakeApiName(AppName).LowerText + '_provider.exe');
    L.Add('```');
    L.Add('');
    L.Add('Both `main.cpp` and `' + cpp_name + '` must be compiled. The `.cpp`');
    L.Add('defines the external symbols and entry points declared in the `.hpp`.');
    L.Add('');

    L.Add('### Step 3 - Start the beacon');
    L.Add('');
    L.Add('Open a new terminal and run:');
    L.Add('');
    L.Add('```bash');
    L.Add('cd LingoFuse-pasAgent-v3/src');
    L.Add('./pascal_agent_service.exe');
    L.Add('```');
    L.Add('');
    L.Add('The beacon listens on `ipc:agent`. Leave this terminal running.');
    L.Add('');

    L.Add('### Step 4 - Start the provider');
    L.Add('');
    L.Add('Open a second terminal and run:');
    L.Add('');
    L.Add('```bash');
    L.Add('cd my_cpp_provider');
    L.Add('LD_LIBRARY_PATH=. ./' + MakeApiName(AppName).LowerText + '_provider     # Linux');
    L.Add('set PATH=%CD%;%PATH% && ' + MakeApiName(AppName).LowerText + '_provider.exe   :: Windows');
    L.Add('```');
    L.Add('');
    L.Add('Expected output:');
    L.Add('');
    L.Add('```');
    L.Add('=== ' + UnitName + ' Tool Provider ===');
    L.Add('Connecting to ipc:agent ...');
    L.Add('');
    L.Add('[OK] Provider is ready. All tools registered.');
    L.Add('Press Enter to shut down.');
    L.Add('```');
    L.Add('');

    L.Add('### Step 5 - Start mcp_api_tool and generate the client config');
    L.Add('');
    L.Add('Open a third terminal:');
    L.Add('');
    L.Add('```bash');
    L.Add('cd LingoFuse-pasAgent-v3/src');
    L.Add('python mcp_api_tool.py --generate-configs --output-dir ./mcp_configs');
    L.Add('```');
    L.Add('');
    L.Add('This produces per-client JSON config files for LM Studio, Claude');
    L.Add('Desktop, Continue.dev, Jan, DeepSeek, and a generic MCP client.');
    L.Add('');
    L.Add('Then start the MCP gateway:');
    L.Add('');
    L.Add('```bash');
    L.Add('python mcp_api_tool.py --transport stdio');
    L.Add('```');
    L.Add('');

    L.Add('### Step 6 - Start the agent (LLM client)');
    L.Add('');
    L.Add('- **LM Studio**: Settings -> MCP Servers -> paste the corresponding');
    L.Add('  `lmstudio_stdio.json` (or `lmstudio_http.json`). Restart.');
    L.Add('- **Claude Desktop**: edit `claude_desktop_config.json`, merge the');
    L.Add('  `mcpServers` section from `claude_stdio.json`, restart.');
    L.Add('- **Continue.dev / Jan / DeepSeek**: merge the corresponding JSON,');
    L.Add('  restart.');
    L.Add('');

    L.Add('### Step 7 - Test the API');
    L.Add('');
    L.Add('In the agent, ask it to call one of the registered tools. For example,');
    L.Add('if the source unit registered `add(a: Int64, b: Int64): Int64`:');
    L.Add('');
    L.Add('```');
    L.Add('Please call the "add" tool with a=5 and b=7.');
    L.Add('```');
    L.Add('');
    L.Add('The agent will:');
    L.Add('');
    L.Add('1. Discover the `add` tool through the beacon.');
    L.Add('2. Build the JSON arguments `{"a": 5, "b": 7}`.');
    L.Add('3. Call through `mcp_api_tool` to your provider.');
    L.Add('4. Receive `{"result": 12}` and present it.');
    L.Add('');
    L.Add('In the provider terminal, the `send_log_async` output (with');
    L.Add('`DEBUG_LOG = true`) shows the same information.');
    L.Add('');
  end;

  procedure EmitToolReference;
  var
    ii, jj: integer;
  begin
    L.Add('## 5. Tool Reference');
    L.Add('');
    L.Add('This section lists every API exposed by the generated provider. Each');
    L.Add('API corresponds to one top-level function of `' + UnitName + '`.');
    L.Add('');

    if Length(ValidFuncs) = 0 then
    begin
      L.Add('> **WARNING: this provider exposes no APIs.**');
      L.Add('>');
      L.Add('> Possible reasons:');
      L.Add('> 1. The source unit has no top-level functions');
      L.Add('>    (nested routines in `class` / `record` are skipped).');
      L.Add('> 2. Every function failed the type check.');
      L.Add('>');
      L.Add('> Supported types: `Int64`, `Double`, `string` only.');
      L.Add('');
      Exit;
    end;

    L.Add('Total APIs: **' + umlIntToStr(Length(ValidFuncs)).Text + '**.');
    L.Add('');
    L.Add('| # | API name | Kind | Params | Return | Description |');
    L.Add('|---|----------|------|--------|--------|-------------|');
    for ii := 0 to High(ValidFuncs) do
    begin
      f := ValidFuncs[ii];
      shortDesc := GetTableCellText(f.Comment);
      if shortDesc.Len > 60 then
        shortDesc := shortDesc.GetString(1, 61) + '...';
      if f.IsFunction then
        row := '| ' + umlIntToStr(ii + 1).Text + ' | `' + MakeApiName(f.Name) + '` | function | ' +
          umlIntToStr(Length(f.Params)).Text + ' | `' + f.ReturnType + '` | ' + shortDesc + ' |'
      else
        row := '| ' + umlIntToStr(ii + 1).Text + ' | `' + MakeApiName(f.Name) + '` | procedure | ' +
          umlIntToStr(Length(f.Params)).Text + ' | - | ' + shortDesc + ' |';
      L.Add(row);
    end;
    L.Add('');

    for ii := 0 to High(ValidFuncs) do
    begin
      f := ValidFuncs[ii];
      desc := GetFullDescription(f.Comment);

      L.Add('### 5.' + umlIntToStr(ii + 1).Text + ' `' + MakeApiName(f.Name) + '`');
      L.Add('');
      L.Add('- Original Pascal function: `' + f.Name + '`');
      L.Add('- Exposed API name: `' + MakeApiName(f.Name) + '`');
      if f.IsFunction then
        L.Add('- Kind: `function`, returns `' + f.ReturnType + '`')
      else
        L.Add('- Kind: `procedure`');
      if desc.Len > 0 then
        L.Add('- Description: ' + desc);
      L.Add('');

      if Length(f.Params) > 0 then
      begin
        L.Add('**Parameters**');
        L.Add('');
        L.Add('| Name | Pascal type | C++ type | JSON type | Description |');
        L.Add('|------|-------------|----------|-----------|-------------|');
        for jj := 0 to High(f.Params) do
        begin
          L.Add('| `' + f.Params[jj].Name + '` | `' + f.Params[jj].PascalType + '` | `' +
            PascalTypeToCPPType(f.Params[jj].PascalType, False) + '` | `' +
            PascalTypeToJsonSchemaType(f.Params[jj].PascalType) + '` | ' +
            GetTableCellText(f.Params[jj].Description) + ' |');
        end;
        L.Add('');
      end;

      L.Add('**Input JSON example**');
      L.Add('');
      L.Add('```json');
      if Length(f.Params) = 0 then
        L.Add('{}')
      else
      begin
        L.Add('{');
        for jj := 0 to High(f.Params) do
        begin
          row := '  "' + f.Params[jj].Name + '": ' + PascalTypeToJsonLiteral(f.Params[jj].PascalType);
          if jj < High(f.Params) then row := row + ',';
          L.Add(row);
        end;
        L.Add('}');
      end;
      L.Add('```');
      L.Add('');

      L.Add('**Output JSON example**');
      L.Add('');
      L.Add('```json');
      if f.IsFunction then
        L.Add('{ "result": ' + PascalTypeToJsonLiteral(f.ReturnType) + ' }')
      else
        L.Add('{ "status": "ok" }');
      L.Add('```');
      L.Add('');
    end;
  end;

  procedure EmitJsonSchemaSpec;
  begin
    L.Add('## 6. JSON Schema Specification');
    L.Add('');
    L.Add('For each tool the provider sends a JSON Schema to the beacon through');
    L.Add('the `register_agent` API. The type whitelist is fixed by the');
    L.Add('normalized `TPascal_Func_Model` output.');
    L.Add('');
    L.Add('| Pascal normalized type | JSON Schema type | C++ type | Example value |');
    L.Add('|------------------------|------------------|----------|---------------|');
    L.Add('| `int64` | `integer` | `std::int64_t` | `42` |');
    L.Add('| `double` | `number` | `double` | `3.14` |');
    L.Add('| `string` | `string` | `std::string` | `"hello"` |');
    L.Add('');
    L.Add('**Every other type** (for example `Boolean`, arrays, records, objects,');
    L.Add('enums, interfaces, function pointers) is **NOT supported**. Functions');
    L.Add('that use them are silently dropped. If you need to pass a complex');
    L.Add('value, serialize it into a `string` first.');
    L.Add('');
  end;

  procedure EmitTroubleshooting;
  begin
    L.Add('## 7. Debugging & Troubleshooting');
    L.Add('');
    L.Add('### 7.1 Global configuration variables');
    L.Add('');
    L.Add('The generated `' + cpp_name + '` defines the following external');
    L.Add('symbols. Edit them at the top of the `.cpp` file to adjust behaviour.');
    L.Add('');
    L.Add('| Name | Default | Purpose |');
    L.Add('|------|---------|---------|');
    L.Add('| `MY_APP_NAME` | `' + UnitName + '` | LingoFuse application name |');
    L.Add('| `MY_APP_DESC` | (auto) | Application description |');
    L.Add('| `IPC_ENDPOINT` | `ipc:agent` | IPC endpoint |');
    L.Add('| `BEACON_APP` | `agent_main_app` | Beacon application name |');
    L.Add('| `REGISTER_API` | `register_agent` | Tool-registration API name |');
    L.Add('| `AGENT_LOG_API` | `agent_log` | Log API name |');
    L.Add('| `DEBUG_LOG` | `false` | Verbose logging toggle |');
    L.Add('');
    L.Add('### 7.2 Common problems');
    L.Add('');
    L.Add('| Symptom | Likely cause | Fix |');
    L.Add('|---------|--------------|-----|');
    L.Add('| `fatal error: json.hpp: No such file or directory` | nlohmann/json not present | Download `json.hpp` from the official releases page |');
    L.Add('| `fatal error: LingoFuse.h: No such file or directory` | Header missing | Use the official header, or the fallback from section 3.1 |');
    L.Add('| `undefined reference to LF_*` | Shared library not linked | Add `-lLingoFuse` and the correct `-L<path>` |');
    L.Add('| Runtime `cannot open shared object file` | Library not on loader path | `export LD_LIBRARY_PATH=.` (Linux) or copy the DLL next to the exe (Windows) |');
    L.Add('| `Execute_And_Reg_all()` returns false | Beacon not running | Start `pascal_agent_service.exe` first |');
    L.Add('| `LF_PrepareDone` returns 0 | Main thread already active in this process | Reuse the runtime, or call `LF_Shutdown` first |');
    L.Add('| Beacon not available in log | `ipc:agent` unreachable | Confirm beacon is running; check firewall |');
    L.Add('| Tool rejected by beacon | Wrong schema, or duplicate name | Check `DEBUG_LOG` output |');
    L.Add('| Tool missing from agent list | Function filtered out | Check param/return types against section 6 whitelist |');
    L.Add('| C++ exception in callback | Exception in user code | All callbacks are wrapped in try/catch; check the log |');
    L.Add('| Linker error on `DEBUG_LOG` | `extern` keyword missing on `const bool` | The generated code already has `extern`; do not remove it |');
    L.Add('');
    L.Add('### 7.3 Enabling detailed logs');
    L.Add('');
    L.Add('Set `DEBUG_LOG` to `true` at the top of `' + cpp_name + '`. Every');
    L.Add('callback then sends its input JSON, its result, and any error to the');
    L.Add('beacon via `agent_log`.');
    L.Add('');
  end;

  procedure EmitCPPPortability;
  begin
    L.Add('## 8. C++ Portability Notes');
    L.Add('');
    L.Add('The generated code targets **C++17** and uses only the standard library');
    L.Add('plus two external dependencies (`json.hpp` and `LingoFuse.h`).');
    L.Add('');
    L.Add('### 8.1 Supported compilers');
    L.Add('');
    L.Add('| Compiler | Minimum version | Notes |');
    L.Add('|----------|-----------------|-------|');
    L.Add('| MSVC | Visual Studio 2019 (16.8) | `/std:c++17` required |');
    L.Add('| g++ | 7.0 | `-std=c++17` required |');
    L.Add('| clang++ | 5.0 | `-std=c++17` required |');
    L.Add('');
    L.Add('### 8.2 Windows specifics');
    L.Add('');
    L.Add('- The generated `.cpp` uses `LF_CDECL`, which expands to `__cdecl` on');
    L.Add('  Windows and to nothing elsewhere. This matches the calling convention');
    L.Add('  that LingoFuse exports.');
    L.Add('- When linking against `LingoFuse.lib` (import library), no additional');
    L.Add('  pragma is required. When using `LoadLibrary` + `GetProcAddress`, see');
    L.Add('  the `LingoFuse.h` header comments.');
    L.Add('');
    L.Add('### 8.3 Static vs dynamic linking');
    L.Add('');
    L.Add('The generated code assumes **dynamic linking** against the LingoFuse');
    L.Add('shared library. Static linking is possible but requires building the');
    L.Add('library from source with a static configuration; that workflow is not');
    L.Add('covered here.');
    L.Add('');
    L.Add('### 8.4 IDE integration');
    L.Add('');
    L.Add('Visual Studio / CLion / VS Code: add `main.cpp`, `' + cpp_name + '`');
    L.Add('and `json.hpp` to the project, then set the include directory to the');
    L.Add('folder containing `LingoFuse.h`, and the library directory to the');
    L.Add('folder containing the LingoFuse binary.');
    L.Add('');
    L.Add('A CMake `CMakeLists.txt` for future use (once `cppAgent` provides a');
    L.Add('config file) is expected to look like:');
    L.Add('');
    L.Add('```cmake');
    L.Add('cmake_minimum_required(VERSION 3.15)');
    L.Add('project(' + MakeApiName(AppName).LowerText + '_provider CXX)');
    L.Add('');
    L.Add('set(CMAKE_CXX_STANDARD 17)');
    L.Add('set(CMAKE_CXX_STANDARD_REQUIRED ON)');
    L.Add('');
    L.Add('find_package(LingoFuse REQUIRED)   # provided by cppAgent');
    L.Add('find_package(nlohmann_json REQUIRED)');
    L.Add('');
    L.Add('add_executable(' + MakeApiName(AppName).LowerText + '_provider');
    L.Add('    main.cpp');
    L.Add('    ' + cpp_name + ')');
    L.Add('');
    L.Add('target_link_libraries(' + MakeApiName(AppName).LowerText + '_provider');
    L.Add('    PRIVATE LingoFuse::LingoFuse nlohmann_json::nlohmann_json)');
    L.Add('```');
    L.Add('');
  end;

  procedure EmitResources;
  begin
    L.Add('## 9. Reference Resources');
    L.Add('');
    L.Add('| Resource | Purpose |');
    L.Add('|----------|---------|');
    L.Add('| `cppAgent` repository (planned) | Official C++ bindings: `LingoFuse.h`, CMake config, sample |');
    L.Add('| nlohmann/json | https://github.com/nlohmann/json |');
    L.Add('| `LingoFuse-pasAgent-v3` repository | Beacon and MCP gateway |');
    L.Add('| `<v3>/src/lingofuse_import.pas` | Reference for the C ABI signatures |');
    L.Add('| `<v3>/src/pascal_agent_service.lpr` | Beacon server source |');
    L.Add('| `<v3>/src/mcp_api_tool.py` | MCP gateway that exposes the tools |');
    L.Add('| `<v3>/src/generate_agent_json.py` | MCP client config generator |');
    L.Add('');
    L.Add('---');
    L.Add('');
    L.Add('_End of document. Generated by `cpp_mcp_generator_tool.pas`._');
    L.Add('');
  end;

begin
  Result := TPascalStringList.Create;
  L := Result;

  if Model = nil then
  begin
    L.Add('# README generation skipped');
    L.Add('');
    L.Add('Reason: supplied `TPascal_Func_Model` is nil.');
    Exit;
  end;

  UnitName := Model.UnitName;
  if UnitName = '' then
  begin
    L.Add('# README generation skipped');
    L.Add('');
    L.Add('Reason: `Model.UnitName` is empty.');
    Exit;
  end;

  AppName := MakeAppNameFromUnit(UnitName);
  hpp_name := MakeSourceFileName(UnitName) + '.hpp';
  cpp_name := MakeSourceFileName(UnitName) + '.cpp';
  ValidFuncs := CollectValidFunctions(Model);

  EmitHeader;
  EmitOverview;
  EmitArchitecture;
  EmitTestProgram;
  EmitBuildTestProcedure;
  EmitToolReference;
  EmitJsonSchemaSpec;
  EmitTroubleshooting;
  EmitCPPPortability;
  EmitResources;

  LogFmt('GenerateCPPReadme: %d lines, %d APIs.',
    [L.Count, Length(ValidFuncs)]);
end;

end.
